### ISSUE TITLE
AppArmor policy error as soon as installed and trying a connection

### ISSUE THREAD

**Issue by bizmate** [tonybolzan/snap-mysql-workbench#16]
Hi

as discussed on the Snap forum at https://forum.snapcraft.io/t/mysql-workbench-wont-start-suddenly-ubuntu-22/32343
as soon as trying to establish a connection there is an error pointing to AppArmor policies blocking workbench.

The [same problem](https://forum.snapcraft.io/t/trouble-finding-a-way-to-reinstall-mysql-workbench-community/25634/3?u=bizmate) was also happening to other users over a year ago so I am surprised this was never raised. 

Not sure what else to add to troubleshoot this problem but do let me know if i can add more info although I personally would just stick to the natively installed version to avoid loosing my data

**Comment by tonybolzan** [comment]
You need do `snap connect mysql-workbench-community:password-manager-service` otherwise you get a AppArmor error when connecting.

To access Keyring you need to connect `password-manager-service` because this interface don’t have Auto Connect. For some reason this explanations are gone from Snap Store. I updated the documentation to match with Readme of github.
