### ISSUE TITLE
Compatibility with Ubuntu 16.04

### ISSUE THREAD

**Issue by cdarken** [tonybolzan/snap-mysql-workbench#2]
Hi. I'm trying to run latest/stable and latest/beta on Ubuntu 16.04 but I get this message: 

![image](https://user-images.githubusercontent.com/1390998/96690642-9c167a00-138c-11eb-9233-03c8ed3f2c3c.png)

It starts, but it's quite unstable, it crashes when I try to add anything to a diagram.
If I run it with -v switch I see a lot of "out of memory" messages then it crashes.
The final message is:
```
(mysql-workbench-bin:27269): glibmm-ERROR **: 11:02:32.289: 
unhandled exception (type std::exception) in signal handler:
what: Could not create font
```

**Comment by tonybolzan** [comment]
The message `Unsupported Operationg System` are normal because of a hard-coded test in workbench core.
This snap run on Ubuntu 18.04 and this msg not reflect in a problem because the deb package inside of snap are for this version of ubuntu.

Probably this instability error is from MySQL Workbench and not from snap.
I'm not affiliated with Oracle and I don't mantain the underlying software.
I don't know how to help you, but fill free do discus with me a workaround
